services:
  proposal-review-assistant:
    image: "ghcr.io/ls1intum/proposal-review-assistant:${IMAGE_TAG}"
    environment:
      PLAYGROUND_USERNAME: ${PLAYGROUND_USERNAME:-playground}
      PLAYGROUND_PASSWORD: ${PLAYGROUND_PASSWORD}
      MODEL_NAME: ${MODEL_NAME}
      IMAGE_MODEL_NAME: ${IMAGE_MODEL_NAME}
      FORMAT_MODEL_NAME: ${FORMAT_MODEL_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      OLLAMA_BASIC_AUTH_USERNAME: ${OLLAMA_BASIC_AUTH_USERNAME}
      OLLAMA_BASIC_AUTH_PASSWORD: ${OLLAMA_BASIC_AUTH_PASSWORD}
      OLLAMA_HOST: ${OLLAMA_HOST}
    restart: unless-stopped
    ports:
      - '7860'
    networks:
      - shared-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-application-server.entryPoints=http"
      - "traefik.http.routers.http-application-server.middlewares=redirect-to-https"
      - "traefik.http.routers.http-application-server.rule=Host(`${APP_HOSTNAME}`) && PathPrefix(`/`)"
      - "traefik.http.routers.https-application-server.entryPoints=https"
      - "traefik.http.routers.https-application-server.rule=Host(`${APP_HOSTNAME}`) && PathPrefix(`/`)"
      - "traefik.http.routers.https-application-server.tls.certresolver=letsencrypt"
      - "traefik.http.routers.https-application-server.tls=true"
      - "traefik.http.routers.http-application-server.priority=5"
      - "traefik.http.routers.https-application-server.priority=10"

networks:
  shared-network:
    name: shared-network
    driver: bridge
