name: Build Docker Images

on:
  push:
    paths:
      - '**/**'
      - '.github/workflows/hyperion_build-and-push-docker.yml'
  release:
    types:
      - created


jobs:
  build:
    name: ${{ matrix.name }}
    if: github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Proposal Review Assistant
            dockerfile: ./Dockerfile
            image: ghcr.io/ls1intum/proposal-review-assistant/app
            context: .
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@feat/minor-build-improvements
    with:
      image-name: ${{ matrix.image }}
      docker-file: ${{ matrix.dockerfile }}
      docker-context: ${{ matrix.context }}
